### ISSUE TITLE
Slow tab changing with redux-logger

### ISSUE THREAD

**Issue by Sunify** [Qwikly/react-native-router-redux#2] opened 2015-11-26 13:14 UTC
When i run app on device with enabled redux-logger middleware, i have really slow (≈10 sec) tab changes. Without middleware all works good.

1. I press on tab
2. Action ROUTER_CHANGE_TAB emits
3. 10 sec freeze
4. Action ROUTER_CHANGE_TAB emits again and then tab really change

**Comment by malkomalko** [comment] 2015-11-26 13:42
I was having similar problems with redux-logger without my routing component on react-native redux applications.  I'll see if I can track this down.

**Comment by malkomalko** [comment] 2015-11-29 15:33
@Sunify I'm going to close this for now and will revisit later.

**Closed by malkomalko** 2015-11-29 15:33 UTC

**Comment by shtefanntz** [comment] 2016-03-24 04:17
Hello everyone,

I can confirm there's a visible overhead due to redux-logger when changing routes. Thanks for pointing it out!

**Comment by tarun29061990** [comment] 2016-10-24 04:50
Its happening for me as well, I removed redux-logger, thunk and there is no middleware in my application, May be there is some other reason for the slow transition. Please help
